[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/.well-known/apple-developer-merchantid-domain-association"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200